### ISSUE TITLE
no charging/discharging info shows up 

### ISSUE THREAD

**Issue by adi1334** [wennaspeedy/batt_consumption_wattmetter#1]
Hi, this would be super useful for me, unfortunately, on my machine there's no charging/discharging info (in watts). 

I wonder if this is due to the fact that on my machine there's no 

`/sys/class/power_supply/BAT0/current_now `

I run Debian Testing on a Thinkpad X1 Extreme. 

Relevant output for `tlp-stat`: 

`+++ ThinkPad Battery Status: BAT0 (Main / Internal)
/sys/class/power_supply/BAT0/manufacturer                   = Celxpert
/sys/class/power_supply/BAT0/model_name                     = 5B10V98091
/sys/class/power_supply/BAT0/cycle_count                    =    326
/sys/class/power_supply/BAT0/energy_full_design             =  80400 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  69240 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  65440 [mWh]
/sys/class/power_supply/BAT0/power_now                      =      0 [mW]
/sys/class/power_supply/BAT0/status                         = Not charging

/sys/class/power_supply/BAT0/charge_control_start_threshold =     90 [%]
/sys/class/power_supply/BAT0/charge_control_end_threshold   =     95 [%]
tpacpi-bat.BAT0.forceDischarge                              =      0

Charge                                                      =   94.5 [%]
Capacity                                                    =   86.1 [%]
` 

Would be cool to have something like this working.

**Comment by adi1334** [comment]
¯\_(ツ)_/¯

**Comment by PaulVanSchayck** [comment]
Same here, I hacked in a function that gets the power from `/sys/class/power_supply/BAT0/power_now`.

**Comment by wennaspeedy** [comment]
Sorry I missed this. Ok I will include power_now in next version.

**Comment by wennaspeedy** [comment]
Ok, next version is up, give me know.

**Comment by adi1334** [comment]
Thank you, it works fine now!
