### ISSUE TITLE
Does not work with Gnome 42 on Debian Testing

### ISSUE THREAD

**Issue by adi1334** [wennaspeedy/batt_consumption_wattmetter#2]
Please update for Gnome 42. When I upgraded, it stopped working.

**Comment by wennaspeedy** [comment]
Current versions works only for 40,41 and 41.5. Please be patient - I will upgrade to 42, but I am still waiting to Endeavour OS (my devel OS) to upgrade to 42 itself.

You can also use one of old versions if works in your case.

**Comment by adi1334** [comment]
Sure thing, will wait. Just wanted to point out the situation. Thank you!

**Comment by wennaspeedy** [comment]
Endeavour was updated to gnome 42. Could you install/update extension?

**Comment by adi1334** [comment]
All good now, thank you!
