### ISSUE TITLE
Wrong display on Thinkpad T480 with 2 batteries

### ISSUE THREAD

**Issue by ehupin** [wennaspeedy/batt_consumption_wattmetter#4]
Hi,

I've used this extension on multiple laptop and it works great, however it does not behave as expected on a Thinkpad T480 with 2 batteries:

- it displays the percentage of battery with more than 10 decimals
- it does not displays the watts when battery selection is set to "automatic" in settings
- it displays the watts properly if I select the battery that is currently used in settings (but still with the 10+ decimals)

I am currently running on Ubuntu 22.04 with gnome 42 and kernel 5.19.

Let me know if I can provide you more information to fix this issue.

Thanks!

**Comment by ehupin** [comment]
I just opened a PR to fix the decimal issues, however I haven't figured out how to deal the the "automatic" battery selection :confused:

**Comment by wennaspeedy** [comment]
Yes, percentage may be problem on laptops with multiple batteries - I don't own any of these. Automatic selection may be easily to fix, but I don't use gnome anymore. It is very buggy environment,  I need stable one, so I switched to cinnamon. No new version of extension will be released in the future.
