### ISSUE TITLE
Customizable separator character

### ISSUE THREAD

**Issue by droserasprout** [wennaspeedy/batt_consumption_wattmetter#7]
Hi again! How about a separator? One could use `|` or `/` or even `⇆`.

**Comment by wennaspeedy** [comment]
Nope,make no sense. By the way gnome 43 and up will not be supported and no more functionality will not be updated, I don't use gnome anymore.

**Comment by droserasprout** [comment]
I'd be glad to contribute code to this extension by myself since it's very useful, and there are no competitors around. So, I ask you to leave these issues open. I can help with maintenance.
