### ISSUE TITLE
Gnome 43 is not supported

### ISSUE THREAD

**Issue by Mimoja** [wennaspeedy/batt_consumption_wattmetter#8]
Not only does the metadata not allow loading on 43, sadly just overwriting the extension will lead to the issue:

```
No JS module 'power' found in search path
```
 Sadly I have no Idea how to debug a gnome extension with this error :/

**Comment by wennaspeedy** [comment]
As described in readme, gnome 43 and up will be not supported. Development is stoped, I don't use gnome anymore.

**Comment by Mimoja** [comment]
Thanks for letting us know and for the awesome work to this point! It was a pleasure :3
