### ISSUE TITLE
Extension has stopped working.

### ISSUE THREAD

**Issue by devangshekhawat** [wennaspeedy/batt_consumption_wattmetter#9]
The extension has stopped working recently.
Tested on Fedora 36 with all the latest updates.
![image](https://user-images.githubusercontent.com/93829532/198849081-fa56bab0-fb14-4ef8-a16c-76049a2eaf06.png)

**Comment by wennaspeedy** [comment]
What gnome version your fedora has?

**Comment by devangshekhawat** [comment]
I am currently on Gnome 42 with the extension version 10.

**Comment by wennaspeedy** [comment]
Ok tell me now what problem is exactly?  After unplug charger, extension doesn't show watt consumption, it shows 0 W only right?

**Comment by devangshekhawat** [comment]
Yes exactly,
even if the charger is plugged in it still shows +0W as depicted in the image below
![image](https://user-images.githubusercontent.com/93829532/198879394-32fa4772-3508-4802-9b3a-97b93e640f5b.png)

**Comment by wennaspeedy** [comment]
How many batteries has your laptop? Tell me more about your laptop please...
Btw did you try choosing battery manually from setting?

**Comment by devangshekhawat** [comment]
My device is HP Pavilion Gaming 15-ec1051ax.
My device shows 3 battery profiles - BAT0, BAT1 and BAT 2. I tried choosing all these profiles manually in the settings and all of the options yielded the following results:
1.  BAT0 - 
![image](https://user-images.githubusercontent.com/93829532/198894066-1866397f-52f8-4567-91b6-261c1125e747.png)
2. BAT1 - 
![image](https://user-images.githubusercontent.com/93829532/198894110-f3faece2-78de-4405-9792-807da92a9bc2.png)
3. BAT2 - 
![image](https://user-images.githubusercontent.com/93829532/198894142-471558dc-5e40-42ac-a4aa-53c018b0b7fa.png)

**Comment by wennaspeedy** [comment]
I don't use gnome DE anymore, so I can't give you more support. Your laptop or Fedora may have different config, I can't help you. Please choose another extension. Sorry for that.
